export { default as about } from "./about";
export { default as catCare } from "./catCare";
export { default as contact } from "./contact";
export { default as facts } from "./facts";
export { default as gallery } from "./gallery";
export { default as home } from "./home";
export { default as questionAnswer } from "./questionAnswer";
export { default as links } from "./links";
export { default as postQuestions } from "./postQuestions";
